apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: test_icatia # Executable ID (max length 64 lowercase-hyphen-separated), please modify this to any value if you are not the only user of your SAP AI Core instance. Example: `first-pipeline-1234`
  annotations:
    scenarios.ai.sap.com/description: "Testing with ICATIA"
    scenarios.ai.sap.com/name: "Tutorial"
    executables.ai.sap.com/description: "Great Job Team"
    executables.ai.sap.com/name: "Hello ICATIA"
  labels:
    scenarios.ai.sap.com/id: "learning"
    ai.sap.com/version: "1.0"
spec:
  entrypoint: icatia
  templates:
  - name: icatia
    steps:
    - - name: greet
        template: greeter

  - name: greeter
    container:
      image: docker.io/python:latest
      command:
        - python3
        - '-c'
      args:
       - |
        print("Hello I'm ICATIA")
